<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$_checkoutSession = $objectManager->get('Magento\Checkout\Model\Session');
$isCheckedPowderCoaing = 0;
$IsSetPowderCoatingColor = "";
if(null !== $_checkoutSession->getIsSetPowderCoating() && $_checkoutSession->getIsSetPowderCoating()=="1"){
	$isCheckedPowderCoaing = 1;	
	$IsSetPowderCoatingColor = $_checkoutSession->getIsSetPowderCoatingColor();	
}
?>
<form id="powder-containg-frm" method="post" actiom="">
<fieldset class="fieldset estimate">
	<legend class="legend">
		<span>Powder Coating</span>
	</legend><br>
	<div class="field" >
		<div class="control">         
			<input class="input-text" <?php echo($isCheckedPowderCoaing)?"checked":"";?> type="Checkbox" name="powder-coating" id="powder-coating" >  <label class="label" for="powder-coating">       
			<span>Select All possible powdercoating products</span>         
		</label>
		</div>
	</div>
	<div class="field" >
		<label class="label" for="powder-color">       
			<span>Powder Color</span>         
		</label>
		<div class="control">         
			<?php /*<input class="input-text" value="<?php echo ($isCheckedPowderCoaing)?$IsSetPowderCoatingColor:""; ?>" type="text" data-validate="{required:true}"  name="powder-color" id="powder-color" > */?>
			<input class="input-text" value="<?php echo $IsSetPowderCoatingColor; ?>" type="text" data-validate="{required:true}"  name="powder-color" id="powder-color" > 
			<input class="input-text" value="0" type="hidden" name="powder-coating-all" id="powder-coating-all" > 
		</div> 
	</div> 
</fieldset>
</form>
<script>
require([
    'jquery',
    'mage/validation',
	 'Magento_Checkout/js/action/get-totals',
    'Magento_Customer/js/customer-data'
], function($,getTotalsAction, customerData){

    var dataForm = $('#powder-containg-frm');
    var ignore = null;

    dataForm.mage('validation', {
        ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
    }).find('input:text').attr('autocomplete', 'off');

    $('#powder-coating').click( function() { //can be replaced with any event
		if($(this).prop("checked") == true){
			$("#powder-coating-all").val(1);
		}
		else if($(this).prop("checked") == false){
			$("#powder-coating-all").val(2);
		}
		
        var validFrm = dataForm.validation('isValid'); //validates form and returns boolean
		
		if(validFrm) {			 
			 var param = dataForm.serialize();
			 $.ajax({
				showLoader: true,
				url: "<?php echo $this->getUrl("addfee/index/addpowdercoating");?>",
				data: param,
				type: "POST"
			}).done(function (data) {
				if(data=="false"){
					location.reload(true);
				}
				/* This is for reloading the minicart */
	/*				var sections = ['cart'];
					customerData.invalidate(sections);
                    customerData.reload(sections, true);
  */
                    /* This is for reloading the totals summary  */
                    var deferred = $.Deferred();
                    getTotalsAction([], deferred);
					
				//alert("hi");
				//$("#block-summary").trigger('contentUpdated');
				return true;
			});
		} else {
			$("#powder-coating").prop("checked", false);
		}
    });
	
	<?php if($isCheckedPowderCoaing){?>
		setTimeout(function(){ //alert("Hello");
			var validFrm = dataForm.validation('isValid');  
		
			if(validFrm) {			 
				 var param = dataForm.serialize();
				 $.ajax({
					showLoader: true,
					url: "<?php echo $this->getUrl("addfee/index/addpowdercoating");?>",
					data: param,
					type: "POST"
				}).done(function (data) {  
					var deferred = $.Deferred();
					getTotalsAction([], deferred); 
					return true;
				});
			}
		}, 5000);			
	<?php }	?>
});

</script>