<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$_checkoutSession = $objectManager->get('Magento\Checkout\Model\Session');
$isCheckedPowderCoaing = 0;
$IsSetPowderCoatingColor = "";
if(null !== $_checkoutSession->getIsSetPowderCoating() && $_checkoutSession->getIsSetPowderCoating()=="1"){
	$isCheckedPowderCoaing = 1;	
	$IsSetPowderCoatingColor = $_checkoutSession->getIsSetPowderCoatingColor();	
}
?>
<form id="powder-containg-frm" method="post" actiom="">
<fieldset class="fieldset estimate">
	<legend class="legend">
		<span>Powdercoat Your Order</span>
	</legend><br>
	<div class="field" >
		<div class="control">         
			<input class="input-text" <?php echo($isCheckedPowderCoaing)?"checked":"";?> type="Checkbox" name="powder-coating" id="powder-coating" >  <label class="label" for="powder-coating">       
			<span>Add ALL Coatable Items</span>         
		</label>
		</div>
	</div>
	<div class="field" >
		<div>
			<div class="upd-pwc-tl">Standard Colours - No Minimum Order Fee</div>
			<div>
				<ul class="pwc-color-choice">
					<li class="pwc-choice-sel <?php echo($IsSetPowderCoatingColor=="RAL1023")?" active":"";?>" data-id="RAL1023"><img src="<?php echo $block->getViewFileUrl('Its_Addfee::images/RAL1023.jpg');?>" alt="RAL1023" /></li>
					<li class="pwc-choice-sel <?php echo($IsSetPowderCoatingColor=="RAL9011")?" active":"";?>" data-id="RAL9011"><img src="<?php echo $block->getViewFileUrl('Its_Addfee::images/RAL9011.jpg');?>" alt="RAL9011" /></li>
					<li class="pwc-choice-sel <?php echo($IsSetPowderCoatingColor=="RAL9003")?" active":"";?>" data-id="RAL9003"><img src="<?php echo $block->getViewFileUrl('Its_Addfee::images/RAL9003.jpg');?>" alt="RAL9003" /></li>
				</ul>
			</div>
		</div>
	</div>
	<div class="field" >
		<div>
			<div class="upd-pwc-tl">Popular Colours - £50 Minimum Order Fee</div>
			<div>
				<ul class="pwc-color-choice">
					<li class="pwc-choice-sel <?php echo($IsSetPowderCoatingColor=="RAL7016")?" active":"";?>" data-id="RAL7016"><img src="<?php echo $block->getViewFileUrl('Its_Addfee::images/RAL7016.jpg');?>" alt="RAL7016" /></li>
					<li class="pwc-choice-sel <?php echo($IsSetPowderCoatingColor=="RAL5005")?" active":"";?>" data-id="RAL5005"><img src="<?php echo $block->getViewFileUrl('Its_Addfee::images/RAL5005.jpg');?>" alt="RAL5005" /></li>
					<li class="pwc-choice-sel <?php echo($IsSetPowderCoatingColor=="RAL3020")?" active":"";?>" data-id="RAL3020"><img src="<?php echo $block->getViewFileUrl('Its_Addfee::images/RAL3020.jpg');?>" alt="RAL3020" /></li>
					<li class="pwc-choice-sel <?php echo($IsSetPowderCoatingColor=="RAL6002")?" active":"";?>" data-id="RAL6002"><img src="<?php echo $block->getViewFileUrl('Its_Addfee::images/RAL6002.jpg');?>" alt="RAL6002" /></li>
				</ul>
			</div>
		</div>
	</div>
	<div class="field" >
		<label class="label" for="powder-color">       
			<span>Enter Any RAL Classic Colour below: £70 Minimum Fee</span>         
		</label>
		<div class="control">         
			<?php /*<input class="input-text" value="<?php echo ($isCheckedPowderCoaing)?$IsSetPowderCoatingColor:""; ?>" type="text" data-validate="{required:true}"  name="powder-color" id="powder-color" > */?>
			<input class="input-text" value="<?php echo $IsSetPowderCoatingColor; ?>" type="text" data-validate="{required:true}"  name="powder-color" id="powder-color" > 
			<input class="input-text" value="0" type="hidden" name="powder-coating-all" id="powder-coating-all" > 
		</div> 
	</div>
	<?php if($isCheckedPowderCoaing){?>
	<div class="field" >
		<div class="upd-pwc-color" style="font-weight: bold;">Update color</div>
	</div>
	<?php } ?>
</fieldset>
</form>
<style>
.upd-pwc-tl{
	font-weight:bold;
	height:0px;
}
ul.pwc-color-choice {
	padding-left:0px;
}
.pwc-color-choice li.active {
	border:1px solid #000;
}
.pwc-color-choice li {
    float: left;
    width: 80px;
    height: 85px;
    padding: 05px;
	list-style:none;	
	cursor:pointer;
}
.pwc-color-choice li img{
    width: 80px;
	height:80px;
}
.upd-pwc-color{
	cursor:pointer;
	text-align:right;
}
</style>

<script>
require([
    'jquery',
    'mage/validation',
	 'Magento_Checkout/js/action/get-totals',
    'Magento_Customer/js/customer-data'
], function($,getTotalsAction, customerData){

    var dataForm = $('#powder-containg-frm');
    var ignore = null;

    dataForm.mage('validation', {
        ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
    }).find('input:text').attr('autocomplete', 'off');

    $('#powder-coating').click( function() { //can be replaced with any event
		if($(this).prop("checked") == true){
			$("#powder-coating-all").val(1);
		}
		else if($(this).prop("checked") == false){
			$("#powder-coating-all").val(2);
		}
		
        var validFrm = dataForm.validation('isValid'); //validates form and returns boolean
		
		if(validFrm) {			 
			 var param = dataForm.serialize();
			 $.ajax({
				showLoader: true,
				url: "<?php echo $this->getUrl("addfee/index/addpowdercoating");?>",
				data: param,
				type: "POST"
			}).done(function (data) {
				if(data=="false"){
					location.reload(true);
				}
				/* This is for reloading the minicart */
	/*				var sections = ['cart'];
					customerData.invalidate(sections);
                    customerData.reload(sections, true);
  */
                    /* This is for reloading the totals summary  */
                    var deferred = $.Deferred();
                    getTotalsAction([], deferred);
					
				//alert("hi");
				//$("#block-summary").trigger('contentUpdated');
				return true;
			});
		} else {
			$("#powder-coating").prop("checked", false);
		}
    });
	
	<?php if($isCheckedPowderCoaing){?>
		setTimeout(function(){ //alert("Hello");
			var validFrm = dataForm.validation('isValid');  
		
			if(validFrm) {			 
				 var param = dataForm.serialize();
				 $.ajax({
					showLoader: true,
					url: "<?php echo $this->getUrl("addfee/index/addpowdercoating");?>",
					data: param,
					type: "POST"
				}).done(function (data) {  
					var deferred = $.Deferred();
					getTotalsAction([], deferred); 
					return true;
				});
			}
		}, 5000);			
	<?php }	?>
	$('.pwc-choice-sel').click( function() { 
		$("#powder-color").val($(this).data("id"));
		
		$('.pwc-choice-sel').removeClass("active");
		$(this).addClass("active");
		$.ajax({
			showLoader: true,
			url: "<?php echo $this->getUrl("addfee/index/addpowdercoatingcolor");?>",
			data: { colorcode : $(this).data("id")},
			type: "POST"
		}).done(function (data) {
			if(data=="false"){
				location.reload(true);
			}				
			var deferred = $.Deferred();                
			return true;
		});
	});
	$('.upd-pwc-color').click( function() {  
		$('.pwc-choice-sel').removeClass("active");
		//$(this).addClass("active");
		$.ajax({
			showLoader: true,
			url: "<?php echo $this->getUrl("addfee/index/addpowdercoatingcolor");?>",
			data: { colorcode : $("#powder-color").val()},
			type: "POST"
		}).done(function (data) {
			location.reload(true);            
			return true;
		});
	});
});

</script>