<?php

/* @var $block \Magento\Catalog\Block\Product\View\Options */
?>
<?php
$dppcHelper = $this->helper('Best4Mage\DPPC\Helper\Data');
$isEnable = $dppcHelper->isEnable();
$isConfigurePrice = $dppcHelper->configurePrice();
?>

<?php $_options = $block->decorateArray($block->getOptions()) ?>
<?php $_productId = $block->getProduct()->getId() ?>
<?php if (count($_options)) :?>
    <?php if ($isEnable == 1 && $isConfigurePrice == 1) { ?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                
                "Best4Mage_DPPC/js/price-options": {
                    "productId" : "<?php echo $_productId; ?>",
                    "optionConfig": <?= /* @escapeNotVerified */ $block->getJsonConfig() ?>,
                    "controlContainer": ".field",
                    "priceHolderSelector": "[data-product-id='<?= $block->escapeHtml($_productId) ?>'][data-role=priceBox]"
                }
                    
            }
        }
    </script>
<?php   } else { ?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "priceOptions": {
                    "optionConfig": <?= /* @escapeNotVerified */ $block->getJsonConfig() ?>,
                    "controlContainer": ".field",
                    "priceHolderSelector": "[data-product-id='<?= $block->escapeHtml($_productId) ?>'][data-role=priceBox]"
                }
            }
        }
    </script>
<?php } ?> 
    <?php foreach ($_options as $_option) : ?>
        <?= $block->getOptionHtml($_option) ?>
    <?php endforeach; ?>
<?php endif; ?>
