<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Magento2.Files.LineLength.MaxExceeded

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper(Magento\Msrp\Helper\Data::class);
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$_checkoutSession = $objectManager->get('Magento\Checkout\Model\Session');
 
$powercoatingItemsTemp = $_checkoutSession->getIsSetPowderCoatingItems();
$powercoatingItems = [];		
$powercoatingItems = unserialize($powercoatingItemsTemp ?? '');
if(!is_array($powercoatingItems)){
	$powercoatingItems = [];
}

$_catalogProduct = $objectManager->get('Magento\Catalog\Model\Product');
?>
<tbody class="cart item">
    <tr class="item-info">
        <td data-th="<?= $block->escapeHtmlAttr(__('Item')) ?>" class="col item">
            <?php if ($block->hasProductUrl()) :?>
                <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"
                   title="<?= $block->escapeHtmlAttr($block->getProductName()) ?>"
                   tabindex="-1"
                   class="product-item-photo">
            <?php else :?>
                <span class="product-item-photo">
            <?php endif;?>
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
            <?php if ($block->hasProductUrl()) :?>
                </a>
            <?php else :?>
                </span>
            <?php endif; ?>
            <div class="product-item-details">
                <strong class="product-item-name">
                    <?php if ($block->hasProductUrl()) :?>
                        <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                    <?php else :?>
                        <?= $block->escapeHtml($block->getProductName()) ?>
                    <?php endif; ?>
                </strong>
                <?php if ($_options = $block->getOptionList()) :?>
                    <dl class="item-options">
                        <?php foreach ($_options as $_option) :?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                            <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                            <dd>
                                <?php if (isset($_formatedOptionValue['full_view'])) :?>
                                    <?= $block->escapeHtml($_formatedOptionValue['full_view']) ?>
                                <?php else :?>
                                    <?= $block->escapeHtml($_formatedOptionValue['value'], ['span', 'a']) ?>
                                <?php endif; ?>
                            </dd>
                        <?php endforeach; ?>
                    </dl>
                <?php endif;?>
                <?php if ($messages = $block->getMessages()) :?>
                    <?php foreach ($messages as $message) :?>
                        <div class= "cart item message <?= $block->escapeHtmlAttr($message['type']) ?>">
                            <div><?= $block->escapeHtml($message['text']) ?></div>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock) :?>
                    <?= $addInfoBlock->setItem($_item)->toHtml() ?>
                <?php endif;?>
				<?php /* start custom code */ $isCheckedPowderCoaing=0;?>
				<?php
				//print_r(get_class_methods($_item));
				$prodObj = $_catalogProduct->load($_item->getProductId());
				//echo $_item->getProductId()."|".$prodObj->getPowder_coating_available(); 
				//exit;
				if($prodObj->getPowder_coating_available()==1){
				?>
				<?php /*<legend class="legend">
					<span>Powder Coating</span>
				</legend><br>*/?>
				<div class="field" >
					<div class="control">         
						<input class="input-text powder-coating-<?php echo $_item->getId();?>" data-id="<?php echo $_item->getProductId();?>" data-sku="<?php echo $_item->getSku();?>" <?php echo(in_array($_item->getSku(),$powercoatingItems))?" checked":"";?> type="Checkbox" name="powder-coating-<?php echo $_item->getId();?>" id="powder-coating-<?php echo $_item->getId();?>" >  <label class="label" for="powder-coating-<?php echo $_item->getId();?>">       
						<span>Add Powdercoating</span>         
					</label>
					</div>
				</div>
				<?php   } echo $_item->getSku(); $prodObj->reset(); /* end custom code */ ?>
				
            </div>
        </td>

        <?php if ($canApplyMsrp) :?>
            <td class="col msrp" data-th="<?= $block->escapeHtmlAttr(__('Price')) ?>">
                <span class="pricing msrp">
                    <span class="msrp notice"><?= $block->escapeHtml(__('See price before order confirmation.')) ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map"
                       id="<?= ($block->escapeHtmlAttr($helpLinkId)) ?>"
                       data-mage-init='{"addToCart":{
                                            "helpLinkId": "#<?= $block->escapeJs($block->escapeHtml($helpLinkId)) ?>",
                                            "productName": "<?= $block->escapeJs($block->escapeHtml($product->getName())) ?>",
                                            "showAddToCart": false
                                            }
                                        }'
                    >
                        <span><?= $block->escapeHtml(__("What's this?")) ?></span>
                    </a>
                </span>
            </td>
        <?php else :?>
            <td class="col price" data-th="<?= $block->escapeHtmlAttr(__('Price')) ?>">
                <?= $block->getUnitPriceHtml($_item) ?>
            </td>
        <?php endif; ?>
        <td class="col qty" data-th="<?= $block->escapeHtmlAttr(__('Qty')) ?>">
            <div class="field qty">
                <div class="control qty">
                    <label for="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty">
                        <span class="label"><?= $block->escapeHtml(__('Qty')) ?></span>
                        <input id="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty"
                               name="cart[<?= $block->escapeHtmlAttr($_item->getId()) ?>][qty]"
                               data-cart-item-id="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                               value="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
                               type="number"
                               size="4"
                               step="any"
                               title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                               class="input-text qty"
                               data-validate="{required:true,'validate-greater-than-zero':true}"
                               data-role="cart-item-qty"/>
                    </label>
                </div>
            </div>
        </td>

        <td class="col subtotal" data-th="<?= $block->escapeHtmlAttr(__('Subtotal')) ?>">
            <?php if ($canApplyMsrp) :?>
                <span class="cart msrp subtotal">--</span>
				<?php else :?>
                <?= $block->getRowTotalHtml($_item) ?>
            <?php endif; ?>
        </td>
    </tr>
    <tr class="item-actions">
        <td colspan="4">
            <div class="actions-toolbar">
                <?= /* @noEscape */ $block->getActions($_item) ?>
            </div>
        </td>
    </tr>
</tbody>

<script>
require([
    'jquery',
    'mage/validation',
	 'Magento_Checkout/js/action/get-totals',
    'Magento_Customer/js/customer-data'
], function($,getTotalsAction, customerData){

    var dataFormItem = $('#powder-containg-frm');
    var ignore = null;

    dataFormItem.mage('validation', {
        ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
    }).find('input:text').attr('autocomplete', 'off');

    $('#powder-coating-<?php echo $_item->getId();?>').click( function(e) { 
		$("#powder-coating-all").val(0);
		//e.preventDefault();
		//alert("call 234");
        var validFrmItem = dataFormItem.validation('isValid'); //validates form and returns boolean
		var setitem =  0;
		if($(this).prop("checked") == true){
			var setitem =  1;
		}
		else if($(this).prop("checked") == false){
			var setitem =  0;
		}
		
		if(validFrmItem) {			 			 
			 $.ajax({
				showLoader: true,
				url: "<?php echo $this->getUrl("addfee/index/addpowdercoatingitem");?>",
				data: { item : $('#powder-coating-<?php echo $_item->getId();?>').data("id"), active : setitem, itemsku : $('#powder-coating-<?php echo $_item->getId();?>').data("sku") },
				type: "POST"
			}).done(function (data) { 	
				if(data=="2"){
					$("#powder-coating-<?php echo $_item->getId();?>").prop("checked", false);
					alert("Powder coating is not avilable for this product.");
					return true;
				} else if(data=="1"){
					$("#powder-coating").prop("checked", true);
				} else {
					$("#powder-coating").prop("checked", false);
					$("#powder-coating-<?php echo $_item->getId();?>").prop("checked", false);
				}
				$(".upd-pwc-color-ctr").show();
				setTimeout(function(){
					//alert("call");
					//$("#powder-coating").click();
					var param = dataFormItem.serialize();
					 $.ajax({
						showLoader: true,
						url: "<?php echo $this->getUrl("addfee/index/addpowdercoating");?>",
						data: param,
						type: "POST"
					}).done(function (data) {  
						var deferred = $.Deferred();
						getTotalsAction([], deferred); 
						return true;
					});
				}, 2000);	
				
				return true;
			});
			setTimeout(function(){
			$('.upd-pwc-color').click();
			}, 2000);
		} else {
			alert("Please enter Poweder Coating Color.");;
			$("#powder-coating-<?php echo $_item->getId();?>").prop("checked", false);
		}
		
		
    });
});

</script>